<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Resources\Pages\CreateRecord;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $totalOrder = 0;
        foreach ($data['orderItems'] as $currentOrderItem) {
            $totalOrder += $currentOrderItem['unit_price'] * $currentOrderItem['quantity'];
        }
        $data['total'] = $totalOrder;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
